[default.extend-words]
copuling = "coupling"
tigher = "tighter"
neccessarly = "necessarily"
arrises = "arises"
moer = "more"
annotaiotn = "annotation"
comonents = "components"
encapsulte = "encapsulate"
proivded = "provided"
beavior = "behavior"
easisly = "easily"
