site_name: Athena Framework
use_directory_urls: true
repo_url: https://github.com/athena-framework/athena
edit_uri: https://github.com/athena-framework/website/tree/master/docs/
site_url: https://athena-framework.github.io/website

theme:
  name: material
  palette:
    scheme: preference
    primary: black
    accent: red
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - gen-files:
      scripts:
        - gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: crystal
      handlers:
        crystal:
          rendering:
            show_source_links: false

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.superfences
  - deduplicate-toc

google_analytics:
  - UA-184169799-1
  - auto

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/athena-framework
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/athena-frameworkcr/community
