site_name: Athena Framework
use_directory_urls: true
strict: true
repo_url: https://github.com/athena-framework/athena
edit_uri: https://github.com/athena-framework/website/tree/master/docs/
site_url: https://athena-framework.github.io/website

theme:
  name: material
  palette:
    scheme: preference
    primary: black
    accent: red
  icon:
    repo: fontawesome/brands/github

plugins:
  - git-revision-date-localized
  - search
  - section-index

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

google_analytics:
  - UA-184169799-1
  - auto

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/athena-framework
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/athena-frameworkcr/community

nav:
  - Introduction: README.md
  - Getting Started: 
    - getting_started/README.md
    - Advanced Usage: getting_started/advanced_usage.md
  - Components:
    - components/README.md
    - Dependency Injection: components/dependency_injection.md
    - Event Dispatcher: components/event_dispatcher.md
    - Config: components/config.md
    - Routing: components/routing.md
    - Serializer: components/serializer.md
    - Validator: components/validator.md
    - Spec: components/spec.md
  - Cookbook:
    - cookbook/README.md
    - Listeners: cookbook/listeners.md
    - Param Converters: cookbook/param_converters.md
    - Exclusion Strategies: cookbook/exclusion_strategies.md
