name: Deploy docs
on: [push, pull_request]
jobs:
  check_spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Spelling
        uses: crate-ci/typos@v1.13.8
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: nightly
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
      - name: Install Python libs
        run: pip3 install --no-deps -r requirements.txt
      - name: Install Crystal libs
        run: shards install
      - name: Build site
        run: mkdocs build --strict
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: mkdocs gh-deploy --force
